### ISSUE TITLE
Question while training

### ISSUE THREAD

**Issue by zcoo** [brownvc/deep-synth#1]
when I do this step:
python continue_train.py --data-dir dataset_location --save-dir save_destination --train-size train_set_size --use-count
There is an error that I have no file "final_categories_frequency"
![image](https://user-images.githubusercontent.com/24472807/45144692-6edcd100-b1f1-11e8-80b5-ce89869f2051.png)
How can I get this file?

**Comment by zcoo** [comment]
Neither do I find this file in github or downloaded files

**Comment by kwang-ether** [comment]
Please double check your `--data-dir` argument, this should point to one of the datasets (bedroom/living/office) generated by `create_data.py`, instead of the original suncg_data. 
`final_categories_frequency` should be automatically created in the process

**Comment by zcoo** [comment]
Thanks a lot!
I succuessfully deal with that.

**Comment by zcoo** [comment]
When I do " python create_data.py "
There is an error:
![1](https://user-images.githubusercontent.com/24472807/45344188-9fe44980-b5d5-11e8-8b93-d1ab09006224.png)
![2](https://user-images.githubusercontent.com/24472807/45344189-a1157680-b5d5-11e8-9f32-80457acf87f6.png)
![3](https://user-images.githubusercontent.com/24472807/45344194-a377d080-b5d5-11e8-9e1b-bcc1ff05c234.png)
I wonder if there are some bugs in code or it's my mistake

This is my environment:
win7 
Anaconda 
python3.6.6 
pytorch0.4.1
with all python libraryin requirements.txt
cuda9.0

**Comment by kwang-ether** [comment]
Should be a problem with Windows only. It's a problem with some code I copied elsewhere in order to suppress the annoying C++ warnings, just comment out the with stdout_redirected() line in the respective file and you should be all set.
An actual fix might come later...

**Comment by liangMaxY** [comment]
@zcoo do you have suncg dataset ？can you share for me ？thank you

**Comment by zcoo** [comment]
@liangMaxY  Of course, you can contact my email!
