### ISSUE TITLE
Data directory structure 

### ISSUE THREAD

**Issue by JackW987** [brownvc/deep-synth#10]
Hi ! I have some problem with the data directory structure.After run the create_data.py I get the bedroom folder with 7000+ images and "coarse_categories_frequency","final_categories_frequency","fine_categories_frequency","model_frequency","model_prior.pkl",Does the data directory structure is true ? Because I get a problem when I run another paper's code which use the data you support,and I get a error "No such file named model_dims.pkl". Looking forward to your reply.

**Comment by kwang-ether** [comment]
https://github.com/brownvc/fast-synth/blob/master/scene-synth/obj_dims.py

**Comment by JackW987** [comment]
> https://github.com/brownvc/fast-synth/blob/master/scene-synth/obj_dims.py

Thanks so much! !!
