### ISSUE TITLE
Adding 3D-Front compatibillity 

### ISSUE THREAD

**Issue by fathyshalaby** [brownvc/deep-synth#11]
I just got access to 3D-Front and wanted to know what I need to do to be able to use it here?

**Comment by kwang-ether** [comment]
3D-Front should be compatible as it also comprises a list of objects (from 3D-FUTURE) and a list of layouts (in the form of jsons).
I haven't gone through parsing 3D-Front myself, but I know this is possible from a few works I've seen. I would encourage you to go through the data processing pipeline and replacing the json/obj handling code with those appropriate for 3D-FRONT.
The json structure, in particular, differs from the dataset we originally used, so there would be quite a bit of work involved I suppose.
The other difference is that, you probably have to create the objs for walls/floor/ceilings yourself as (I think) 3D-FRONT describes these in polygons. I think I have some code for doing so in the planit repo but I can't recall.
