### ISSUE TITLE
How can I render door and window data

### ISSUE THREAD

**Issue by JackW987** [brownvc/deep-synth#12]
Thanks for your wonderful works about deal with suncg data.
I have some problem about TopDownView.render() function.
when I render bedroom , I get the (visualization,(floor,wall,nodes)),but I want to get the (floor,wall,window,door,nodes),I can't find options that can make window and door information add in the tuple.So how can I render door and window data in the bedroom dataset.
Looking forward to your reply.
![job](https://user-images.githubusercontent.com/25745086/130211655-3306bf27-fddb-4c1f-9ee3-221bab721083.jpg)

**Comment by kwang-ether** [comment]
If I recall correctly, doors and windows are part of nodes.This (https://github.com/brownvc/deep-synth/blob/b800e11290b763b58e7d3b30329769a7b77cd12a/deep-synth/data/rendered.py#L77-L85) is an example that handles them.

**Comment by JackW987** [comment]
> If I recall correctly, doors and windows are part of nodes.This (
> 
> https://github.com/brownvc/deep-synth/blob/b800e11290b763b58e7d3b30329769a7b77cd12a/deep-synth/data/rendered.py#L77-L85
> 
> ) is an example that handles them.

Thanks for your reply! I get it

**Comment by k-bobin** [comment]
> Thanks for your wonderful works about deal with suncg data. I have some problem about TopDownView.render() function. when I render bedroom , I get the (visualization,(floor,wall,nodes)),but I want to get the (floor,wall,window,door,nodes),I can't find options that can make window and door information add in the tuple.So how can I render door and window data in the bedroom dataset. Looking forward to your reply. ![job](https://user-images.githubusercontent.com/25745086/130211655-3306bf27-fddb-4c1f-9ee3-221bab721083.jpg)


hi I'm having a hard time to find person who still has access to SUNCG dataset
if you still have one, could you please share it for me or email me?

My email is kbb8009@gmail.com
