### ISSUE TITLE
Source Dataset

### ISSUE THREAD

**Issue by hanamizukigakki** [brownvc/deep-synth#6]
Hi,
   Thanks for your job and i really appreciate it, now i get an problem that the main page of the SUNCG dataset seems lost, it would be great if you could share the dataset. Thanks for your job again.

**Comment by kwang-ether** [comment]
Unfortunately I don't think we are allowed to do so. I would recommend you contact the authors of the dataset regarding the status of the dataset. 
Apologies for the incovenience.
